AWSTemplateFormatVersion: 2010-09-09
Description: Mambu API Proxy Implementation
Parameters:
  StageName:
    Type: String
    Default: dev
    Description: Prefix for Env Name
  SFHostName:
    Type: String
    Description: SF Environment Hostname
    Default: myorg--poc.my.salesforce.com
  SFAPIPath:
    Type: String
    Description: SF API Context
    Default: /services/apexrest/api
  SFAuthUrl:
    Type: String
    Description: SF Auth Url
    Default: test.salesforce.com
  SFAuthUrlPath:
    Type: String
    Description: SF Auth Url Path
    Default: /services/oauth2/token
  SFAuthUsername:
    Type: String
    Description: SF Auth Username
    NoEcho: 'true'
  SFAuthPassword:
    Type: String
    Description: SF Auth Password
    NoEcho: 'true'
  SFConsumerKey:
    Type: String
    Description: SF API Consumer Key
    NoEcho: 'true'
  SFConsumerSecret:
    Type: String
    Description: SF API Consumer Secret
    NoEcho: 'true'
  MinimumCompressionSize:
    Type: Number
    Default: 10485760
    Description: Minimum Compression Size for content encoding
  CustomDomain:
    Type: String
    Default: dev.api.example.com
    Description: Custom Domain for the API (This should be an existing API Custom Domain as this template doesn't create one)
  BasePath:
    Type: String
    Default: sf
    Description: Base path for API
  CertificateArn:
    Type: String
    Default: arn:aws:acm:eu-west-2:213074200201:certificate/24b3ade0-e642-489a-94dd-d088050bd717
    Description: Arn of an validated ACM certificate

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref CustomDomain, '']]
  HasCertificateArn: !Not [!Equals [!Ref CertificateArn, '']]
  HasCustomDomainEnabled: !And [Condition: HasCustomDomain, Condition: HasCertificateArn ]

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Mambu API Proxy Configuration
        Parameters:
          - StageName
          - SFHostName
          - SFAPIPath
          - SFAuthUrl
          - SFAuthUrlPath
          - SFAuthUsername
          - SFAuthPassword
          - SFConsumerKey
          - SFConsumerSecret
          - MinimumCompressionSize
          - CustomDomain
          - BasePath
          - CertificateArn

Resources:
  usagePlanPremium:
    DependsOn:
    - Deployment
    Type: 'AWS::ApiGateway::UsagePlan'
    Properties:
      ApiStages:
        - ApiId: !Ref RestAPI
          Stage: !Ref StageName
      Description: Premium usage plan
      # Quota:
      #   Limit: 9999999
      #   Period: DAY
      Throttle:
        BurstLimit: 1000000
        RateLimit: 1000000
      UsagePlanName: !Sub '${StageName}-SF-Premium-Plan'

  AuthUsername:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Username for SF Authentication
      Name: !Sub '${StageName}-SF-Username'
      SecretString: !Ref SFAuthUsername
      Tags:
        - Key: Name
          Value: !Sub '${StageName}-SF-Username'

  AuthPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Password for SF Authentication
      Name: !Sub '${StageName}-SF-Password'
      SecretString: !Ref SFAuthPassword
      Tags:
        - Key: Name
          Value: !Sub '${StageName}-SF-Password'

  ConsumerKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: SF ConsumerKey
      Name: !Sub '${StageName}-SF-ConsumerKey'
      SecretString: !Ref SFConsumerKey
      Tags:
        - Key: Name
          Value: !Sub '${StageName}-SF-ConsumerKey'

  ConsumerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: SF ConsumerSecret
      Name: !Sub '${StageName}-SF-ConsumerSecret'
      SecretString: !Ref SFConsumerSecret
      Tags:
        - Key: Name
          Value: !Sub '${StageName}-SF-ConsumerSecret'

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      CustomerId: PremiumUser
      GenerateDistinctId: true
      Name: !Sub '${StageName}-SF-Premium-Plan-Key'
      Enabled: true

  usagePlanKey:
    Type: 'AWS::ApiGateway::UsagePlanKey'
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref usagePlanPremium

  LambdaBasicExecution:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Path: /

  SecretsManagerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: secret-manager-read
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: LambdaSecretManagerRead
          Effect: Allow
          Action:
            - secretsmanager:GetRandomPassword
            - secretsmanager:GetResourcePolicy
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            - secretsmanager:ListSecretVersionIds
            - secretsmanager:ListSecrets
          Resource:
          - "*"
      Roles:
        - !Ref LambdaBasicExecution

  lambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt proxyLambdaFn.Arn
      Principal: apigateway.amazonaws.com

  proxyLambdaFn:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: !GetAtt LambdaBasicExecution.Arn
      Handler: index.handler
      Environment:
        Variables:
          auth_password: !Ref AuthPassword
          auth_url: !Ref SFAuthUrl
          auth_url_path: !Ref SFAuthUrlPath
          auth_username: !Ref AuthUsername
          consumer_key: !Ref ConsumerKey
          consumer_secret: !Ref ConsumerSecret
          sf_api_host: !Ref SFHostName
          sf_api_path: !Ref SFAPIPath
          base_path: !Sub '/${BasePath}'
      Code:
        ZipFile: |
          const https = require('https');
          const queryString = require('querystring');
          let basePath = process.env.base_path
          let authUrl = process.env.auth_url;
          let authUrlPath = process.env.auth_url_path;
          let authUsername = process.env.auth_username;
          let authPassword = process.env.auth_password;
          let consumerKey = process.env.consumer_key;
          let consumerSecret = process.env.consumer_secret;
          let sfApiHost = process.env.sf_api_host;
          let sfApiPath = process.env.sf_api_path;
          let region = process.env.AWS_REGION;
          var AWS = require('aws-sdk');
          // Create a Secrets Manager client
          var client = new AWS.SecretsManager({
            region: region
          });
          exports.handler = async function (event, context) {
            let authUsernameUe = await getSecretValue(context, authUsername);
            let authPasswordUe = await getSecretValue(context, authPassword);
            let consumerKeyUe = await getSecretValue(context, consumerKey);
            let consumerSecretUe = await getSecretValue(context, consumerSecret);
            let postData = queryString.stringify({
              'grant_type': 'password',
              'client_id': consumerKeyUe,
              'client_secret': consumerSecretUe,
              'username': authUsernameUe,
              'password': authPasswordUe
            });
            let options = {
              hostname: authUrl,
              path: authUrlPath,
              method: 'POST',
              headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'Content-Length': postData.length
              }
            };
            const promise = await makeCall(options, postData);
            let accessToken = JSON.parse(promise).access_token;
            let qs = queryString.stringify(event.queryStringParameters);
            let sfPath = sfApiPath  + event.path + '?' + qs;
            sfPath = sfPath.replace(basePath, "");
            let sfMethod = 'GET';
            let sfOptions = {
              hostname : sfApiHost,
              path : sfPath,
              method: sfMethod,
              headers: {
                'Authorization': 'OAuth ' + accessToken
              }
            };
            const sfPromise = await makeCall(sfOptions);
            const response = {
              statusCode: 200,
              body: sfPromise,
            };
            return response;
          };
          function makeCall(options, postData = '') {
            return new Promise(function (resolve, reject) {
              const request = https.request(options, (res) => {
                var finalData = '';
                res.on('data', function (data) {
                  finalData += data;
                });
                res.on('end', function (data) {
                  resolve(finalData);
                });
              });
              request.on('error', (e) => {
                reject(e);
              });
              request.write(postData);
              request.end();
            });
          }
          function getSecretValuePromise(context, secretId) {
            return new Promise((resolve, reject) => {
              client.getSecretValue({SecretId: secretId}, function(err, data) {
                if (err) {
                  console.log("Get Secret got an error: " + err.message);
                  reject(err);
                } else {
                  // Decrypts secret using the associated KMS CMK.
                  // Depending on whether the secret is a string or binary, one of these fields will be populated.
                  if ('SecretString' in data) {
                    let secret = data.SecretString;
                    resolve(secret);
                  } else {
                    let buff = new Buffer(data.SecretBinary, 'base64');
                    let decodedBinarySecret = buff.toString('ascii');
                    resolve(decodedBinarySecret);
                  }
                }
              });
            });
          }
          async function getSecretValue(context, secretId) {
            try {
              let promise = getSecretValuePromise(context, secretId);
              let indices = await promise;
              return indices;
            } catch (error) {
              console.log(error);
              return "";
            }
          }
      Description: Invoke a function during api Invocation.

  CustomDomainBasePathMapping:
    Condition: HasCustomDomainEnabled
    DependsOn:
    - Deployment
    Properties:
      BasePath: !Ref BasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref RestAPI
      Stage: !Ref StageName
    Type: AWS::ApiGateway::BasePathMapping

  Deployment:
    DependsOn:
    - Methodproxy
    Properties:
      RestApiId:
        Ref: RestAPI
      StageName: !Ref StageName
    Type: AWS::ApiGateway::Deployment

  Methodproxy:
    DependsOn:
    - proxyLambdaFn
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref ResourceRoot
      ApiKeyRequired: true
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${proxyLambdaFn.Arn}/invocations
    Type: AWS::ApiGateway::Method

  ResourceRoot:
    DependsOn:
    - RestAPI
    Properties:
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: '{proxy+}'
      RestApiId: !Ref RestAPI
    Type: AWS::ApiGateway::Resource

  RestAPI:
    Properties:
      ApiKeySourceType: HEADER
      MinimumCompressionSize: !Ref MinimumCompressionSize
      EndpointConfiguration:
        Types:
        - REGIONAL
      Name:
        Ref: AWS::StackName
      Policy:
        Statement:
        - Action:
          - execute-api:Invoke
          Effect: Allow
          Principal: '*'
          Resource:
          - '*'
        Version: 2012-10-17
    Type: AWS::ApiGateway::RestApi

  WAFAcl:
    Properties:
      DefaultAction:
        Allow: {}
      Description: This is an example WebACL
      Name:
        Ref: AWS::StackName
      Rules:
      - Name: RuleWithAWSManagedRules
        OverrideAction:
          Count: {}
        Priority: 0
        Statement:
          ManagedRuleGroupStatement:
            Name: AWSManagedRulesCommonRuleSet
            VendorName: AWS
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: RuleWithAWSManagedRulesMetric
          SampledRequestsEnabled: true
      - Name: RuleWithAWSManagedLinuxnRules
        OverrideAction:
          Count: {}
        Priority: 4
        Statement:
          ManagedRuleGroupStatement:
            Name: AWSManagedRulesLinuxRuleSet
            VendorName: AWS
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: RuleWithAWSManagedLinuxRulesMetric
          SampledRequestsEnabled: true
      - Name: RuleWithAWSManagedIPReputationRules
        OverrideAction:
          Count: {}
        Priority: 5
        Statement:
          ManagedRuleGroupStatement:
            Name: AWSManagedRulesAmazonIpReputationList
            VendorName: AWS
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: RuleWithAWSManagedIPReputationRulesMetric
          SampledRequestsEnabled: true
      - Name: RuleWithAWSManagedAdminProtectionRules
        OverrideAction:
          Count: {}
        Priority: 6
        Statement:
          ManagedRuleGroupStatement:
            Name: AWSManagedRulesAdminProtectionRuleSet
            VendorName: AWS
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: RuleWithAWSManagedAdminProtectionRulesMetric
          SampledRequestsEnabled: true
      - Name: RuleWithAWSManagedKnownBadInputsRules
        OverrideAction:
          Count: {}
        Priority: 2
        Statement:
          ManagedRuleGroupStatement:
            Name: AWSManagedRulesKnownBadInputsRuleSet
            VendorName: AWS
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: RuleWithAWSManagedKnownBadInputsRulesMetric
          SampledRequestsEnabled: true
      - Name: RuleWithAWSManagedSQLInjectInputsRules
        OverrideAction:
          Count: {}
        Priority: 3
        Statement:
          ManagedRuleGroupStatement:
            Name: AWSManagedRulesSQLiRuleSet
            VendorName: AWS
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: RuleWithAWSManagedSQLInjectInputsRulesMetric
          SampledRequestsEnabled: true
      - Action:
          Block: {}
        Name: BlockXssAttack
        Priority: 1
        Statement:
          XssMatchStatement:
            FieldToMatch:
              AllQueryArguments: {}
            TextTransformations:
            - Priority: 1
              Type: NONE
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: BlockXssAttackMetric
          SampledRequestsEnabled: true
      Scope: REGIONAL
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName:
          Fn::Sub: ${AWS::StackName}WebACLMetric
        SampledRequestsEnabled: true
    Type: AWS::WAFv2::WebACL

  WAFAssociation:
    DependsOn:
    - Deployment
    Properties:
      ResourceArn: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${RestAPI}/stages/${StageName}"
      WebACLArn: !GetAtt WAFAcl.Arn
    Type: AWS::WAFv2::WebACLAssociation
